In [1]:
# env includes
import requests
# part of Python standard library
import json
import sqlite3

In [3]:
# Define the URL and make the request using the API (incl key)
url= "https://api.jcdecaux.com/vls/v1/stations?contract=Dublin&apiKey=7b9a350297fefef5f4147e65b6bc3114aacde014"
jsonText = requests.get(url).text

# Create a json file to hold the intermediate data
with open("text.json", 'w') as fout:
    fout.write(jsonText)

# Handle the json data from the open file
jsonData = json.load(open('text.json', 'r'))

# Render the data from the file
# for i in jsonData:
#     freeBikes = i["bike_stands"] - i["available_bike_stands"]
#     print("Station Number:",
#         i["number"],
#           "\n",
#         i["name"], 
#           "\n", 
#           "Bike Stands:", 
#           i["bike_stands"], 
#           "\n", 
#           "Stands Available:", 
#           i["available_bike_stands"],
#           "\n",
#           "Free Bikes:",
#           freeBikes,
#           end="\n\n")

# Extract data points from dictionary
# print(json[number])
for i in jsonData:
    print(i['number'])
#     for j in i:
#         print(j,":", i[j])
#     print("\n\n")

42
30
54
108
56
6
18
32
52
48
13
43
81
31
98
14
23
106
112
68
74
87
84
90
11
17
45
114
72
63
113
91
99
9
67
55
62
5
97
61
77
73
4
49
19
7
60
102
38
53
58
66
104
101
115
47
8
27
16
96
82
76
71
79
69
25
51
37
59
95
94
105
36
93
22
50
110
12
34
78
2
75
111
26
65
15
86
35
10
100
24
64
109
85
107
33
44
89
57
80
41
3
46
40
29
70
103
28
39
83
92
21
88

In [46]:
# Create a connection object for sqlite db
# conn = sqlite3.connect("test.db")

# Return a cursor object from the connection
# c = conn.cursor()
# Define SQL statement and execute
# c.execute("""CREATE TABLE employees(
#             id int primary key,
#             firstName text ,
#             surname text,
#             email text)""")
# Commit the changes
# conn.commit()

# conn.close()
# help(sqlite3)

try:
    conn = sqlite3.connect("test.db")
    c = conn.cursor()
    c.execute("INSERT INTO employees VALUES('1', 'Mike', 'Du Maus', 'dumaus@email.com')")
    conn.commit()
except sqlite3.IntegrityError as e:
    print(e, "::Primary Key attribute must be unique::")
# conn.close()

conn2 = sqlite3.connect("test.db")
c = conn.cursor()
c.execute("SELECT * FROM employees")
# fetchall returns the whole set of tuples in a list
# print(c.fetchall())
print(c.fetchone())
print(c.fetchmany())

# conn.commit() 
# no need to commit because nothing has changed

UNIQUE constraint failed: employees.id ::Primary Key attribute must be unique::
(1, 'Mike', 'Du Maus', 'dumaus@email.com')
[]

In [47]:
# print(jsonData)

In [48]:
try:
    conn = sqlite3.connect("set1.db")
    c = conn.cursor()
    c.execute("""
    CREATE TABLE dublin(
             number int primary key,
             name text ,
             address text,
             postion text
    
    )""")
    c.execute(" INSERT INTO dublin VALUES ('1', 'bob', 'bob', 'CLOSEBY')")
    conn.commit()
#     conn.close()
except sqlite3.OperationalError as e:
    print(e, "::Review code or specify a different DB::")

table dublin already exists ::Review code or specify a different DB::

In [49]:

# dicn = {}
# for i in jsonData:
#     for j in i:
#         dicn[j] = i[j]
#     print(dicn)
#     dic = dicn[""]
#     c.execute("INSERT INTO dublin_data VALUES (:number, :name, :address)", dicn)
#     c.execute("INSERT INTO dublin_data VALUES ('1', 'bob')")
#     conn.commit()



# print(dicn)
        

        
        #         dicn[]
#     c.execute("INSERT INTO dublin_data VALUES(':Number', ':Name', ':Address', :Position[0], :Positions[1]),", dicn)

In [64]:
number = jsonData[2]['number']
name = jsonData[2]['name']
address = jsonData[2]['address']
position = jsonData[2]['contract_name']
conn = sqlite3.connect("set1.db")
c = conn.cursor()
c.execute(" INSERT INTO dublin VALUES (?,?,?,?)", (number, name, address, position))
conn.commit()

conn = sqlite3.connect("set1.db")
c = conn.cursor()
c.execute("SELECT * FROM dublin")
print(c.fetchall())
print(d)

[(1, 'bob', 'bob', 'CLOSEBY'), (2, 'jim', 'jim', 'CLOSE'), (3, 'jim', 'jim', 'CLOSE'), (4, 'jim', 'jim', 'CLOSE'), (5, 'jim', 'jim', 'CLOSE'), (9, 'jim', 'jim', 'CLOSE'), (42, 'jim', 'jim', 'CLOSE'), (30, 'jim', 'jim', 'CLOSE'), (54, 'CLONMEL STREET', 'Clonmel Street', 'Dublin')]
{'number': 2, 'name': 'jim', 'address': 'jim', 'position': 'CLOSEBY'}